version: '3'
services:
  web:
    build: .
    # ports:
    # - "1337:1337"
    restart: unless-stopped
    networks:
      - web
      - default
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.pizzapi.frontend.rule=Host:pizza-pi.simon-neutert.de"
      - "traefik.pizzapi.port=80"
      - "traefik.pizzapi.protocol=http"

networks:
  web:
    external: true