version: '3'
services:
  web:
    build: .
    ports:
    - "8080:80"
    restart: unless-stopped
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"

      - "traefik.http.routers.robotcityguide_website.entrypoints=web"
      - "traefik.http.routers.robotcityguide_website.rule=Host(`www.robotcityguide.de`)"
      - "traefik.http.routers.robotcityguide_website.middlewares=https_redirect"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      
      - "traefik.http.routers.robotcityguide_website_https.entrypoints=websecure"
      - "traefik.http.routers.robotcityguide_website_https.rule=Host(`www.robotcityguide.de`)"
      
      - "traefik.http.routers.robotcityguide_website_https.tls.certresolver=myhttpchallenge"
      - "traefik.http.services.robotcityguide_website.loadbalancer.server.port=80"
      - "trarfik.http.services.robotcityguide_website.loadbalancer.server.port=443"

networks:
  web:
    external: true