version: '3'

services:
  web:
    build: .
    restart: unless-stopped
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"

      - "traefik.http.routers.pizzapi.entrypoints=web"
      - "traefik.http.routers.pizzapi.rule=Host(`pizza-pi.simon-neutert.de`)"
      - "traefik.http.routers.pizzapi.middlewares=https_redirect"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      
      - "traefik.http.routers.pizzapi_https.entrypoints=websecure"
      - "traefik.http.routers.pizzapi_https.rule=Host(`pizza-pi.simon-neutert.de`)"
      
      - "traefik.http.routers.pizzapi_https.tls.certresolver=myhttpchallenge"
      - "traefik.http.services.pizzapi.loadbalancer.server.port=80"
      - "trarfik.http.services.pizzapi.loadbalancer.server.port=443"

networks:
  web:
    external: true