version: '3'
services:
  web:
    build: .
    ports:
    - "8080:80"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.hitchi.frontend.rule=Host:pizza-pi.simon-neutert.de"
      - "traefik.hitchi.port=8080"
      - "traefik.hitchi.protocol=http"

networks:
  web:
    external: true